/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bisulibraryarchives;

import javax.swing.JOptionPane;

/**
 *
 * @author Keth Dominic
 */
public class LoginPanel extends javax.swing.JFrame {
    
    String userName, password;

    /**
     * Creates new form LoginPanel
     */
    QueryProcessor qp;
    
    public LoginPanel() {
        initComponents();
        qp = new QueryProcessor();
        regPanel.hide();
        loginInfo();
    }
    
    public void loginInfo(){
        String checkrem = qp.getSpecificField("Select `rem_id` from `remember` where `rem_id` = 1");
        if(checkrem != null){
            user.setText(qp.getSpecificField("Select `username` from `remember` where `rem_id` = 1"));
            pass.setText(qp.getSpecificField("Select `pass` from `remember` where `rem_id` = 1"));
        }
    } 
    
    public void login(){
        userName = qp.getSpecificField("SELECT `username` FROM `users_info` where `username` = '"+user.getText()+"'");
         password = qp.getSpecificField("SELECT `password` FROM `users_info` where `password` = '"+pass.getText()+"'");
         System.out.println("user"+ userName+"pass "+password);
         
         if(user.getText().equals(userName) ||  pass.getText().equals(password)){
            if(user.getText().equals(userName) && pass.getText().equals(password)){

                MainMenu main = new MainMenu();
                main.setVisible(true);
                this.dispose();
            }
            else{
                errorlbl.setText("Wrong user or password!");

            }
         }
         else{
             errorlbl.setText("No account found!");
             user.setText("");
                pass.setText("");
             
         }
         
         if (remCheckBox.isSelected()){
          String checkrem = qp.getSpecificField("Select `rem_id` from `remember` where `rem_id` = 1");
          if(checkrem == null){
               qp.executeUpdate("Insert into `remember` (`rem_id`, `username`, `pass`) values( 1 ,'"+user.getText()+"','"+pass.getText()+"') "); 
           }
           else{
               qp.executeUpdate("Update `remember` SET `username` ='"+user.getText()+"', `pass` ='"+pass.getText()+"' where `rem_id` = 1");  
           }        
       }
           
    }
    
    public void regUser(){ 
        
        try{
       qp.executeUpdate("INSERT INTO `users_info`(`id`, `first_name`, `middle_i`, `last_name`, `age`, `address`, `course`, `year`, `block`, `username`, `password`) VALUES (NULL, '"
         +firstName.getText()+"','"+middle.getText()+"','"+lastName.getText()+"','"+age.getText()+"','"+address.getText()+"','"+course.getText()
         +"','"+year.getSelectedItem()+"','"+block.getSelectedItem()+"','"+regUsername.getText()+"','"+regPass.getText()+"')");
        
       JOptionPane.showMessageDialog(null, "Successfully Registered");
        }
        catch  (Exception e){
            JOptionPane.showMessageDialog(null, "Failed to register");
        }
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signinbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        remCheckBox = new javax.swing.JCheckBox();
        errorlbl = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        regPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        middle = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();
        regLogin = new javax.swing.JButton();
        firstName = new javax.swing.JTextField();
        course = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        block = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        lastName = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        regPass = new javax.swing.JTextField();
        regUsername = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(null);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BISU");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginPanel.add(jLabel1);
        jLabel1.setBounds(60, 80, 180, 30);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Library and Archives");
        loginPanel.add(jLabel2);
        jLabel2.setBounds(60, 100, 180, 30);

        user.setForeground(new java.awt.Color(153, 153, 255));
        user.setText("Username");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        loginPanel.add(user);
        user.setBounds(50, 170, 210, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/icons8_person_28px.png"))); // NOI18N
        loginPanel.add(jLabel4);
        jLabel4.setBounds(20, 170, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/icons8_forgot_password_28px.png"))); // NOI18N
        loginPanel.add(jLabel5);
        jLabel5.setBounds(20, 220, 30, 30);

        signinbtn.setBackground(new java.awt.Color(0, 102, 255));
        signinbtn.setForeground(new java.awt.Color(255, 255, 255));
        signinbtn.setText("Sign-up");
        signinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtnActionPerformed(evt);
            }
        });
        loginPanel.add(signinbtn);
        signinbtn.setBounds(110, 360, 72, 22);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("or");
        loginPanel.add(jLabel3);
        jLabel3.setBounds(140, 310, 11, 16);

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        loginPanel.add(jButton3);
        jButton3.setBounds(100, 280, 90, 22);

        remCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        remCheckBox.setForeground(new java.awt.Color(0, 102, 255));
        remCheckBox.setText("Remember me");
        loginPanel.add(remCheckBox);
        remCheckBox.setBounds(50, 250, 120, 20);

        errorlbl.setForeground(new java.awt.Color(255, 0, 0));
        errorlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginPanel.add(errorlbl);
        errorlbl.setBounds(50, 150, 200, 0);

        pass.setForeground(new java.awt.Color(153, 153, 153));
        pass.setText("*********");
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        loginPanel.add(pass);
        pass.setBounds(50, 220, 210, 30);

        mainPanel.add(loginPanel);
        loginPanel.setBounds(440, 20, 280, 440);

        regPanel.setBackground(new java.awt.Color(255, 255, 255));
        regPanel.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BISU");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regPanel.add(jLabel6);
        jLabel6.setBounds(50, 10, 180, 30);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Library and Archives");
        regPanel.add(jLabel7);
        jLabel7.setBounds(50, 30, 180, 30);

        middle.setForeground(new java.awt.Color(0, 102, 255));
        middle.setText("M.I");
        middle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                middleMouseClicked(evt);
            }
        });
        middle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleActionPerformed(evt);
            }
        });
        regPanel.add(middle);
        middle.setBounds(200, 80, 60, 30);

        pass1.setForeground(new java.awt.Color(0, 102, 255));
        pass1.setText("Re-type Password");
        pass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass1MouseClicked(evt);
            }
        });
        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });
        regPanel.add(pass1);
        pass1.setBounds(20, 320, 240, 30);

        regLogin.setBackground(new java.awt.Color(0, 102, 255));
        regLogin.setForeground(new java.awt.Color(255, 255, 255));
        regLogin.setText("Login");
        regLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regLoginActionPerformed(evt);
            }
        });
        regPanel.add(regLogin);
        regLogin.setBounds(110, 400, 70, 22);

        firstName.setForeground(new java.awt.Color(0, 102, 255));
        firstName.setText("First Name");
        firstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstNameMouseClicked(evt);
            }
        });
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        regPanel.add(firstName);
        firstName.setBounds(20, 80, 170, 30);

        course.setForeground(new java.awt.Color(0, 102, 255));
        course.setText("Course");
        course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseMouseClicked(evt);
            }
        });
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        regPanel.add(course);
        course.setBounds(20, 200, 90, 30);

        age.setForeground(new java.awt.Color(0, 102, 255));
        age.setText("Age");
        age.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ageMouseClicked(evt);
            }
        });
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        regPanel.add(age);
        age.setBounds(200, 120, 60, 30);

        address.setForeground(new java.awt.Color(0, 102, 255));
        address.setText("Address");
        address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressMouseClicked(evt);
            }
        });
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        regPanel.add(address);
        address.setBounds(20, 160, 240, 30);

        block.setForeground(new java.awt.Color(0, 102, 255));
        block.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Block", "A", "B", "C", "D" }));
        regPanel.add(block);
        block.setBounds(190, 200, 70, 30);

        year.setForeground(new java.awt.Color(0, 102, 255));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1", "2", "3", "4" }));
        regPanel.add(year);
        year.setBounds(120, 200, 60, 30);

        lastName.setForeground(new java.awt.Color(0, 102, 255));
        lastName.setText("Last Name");
        lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastNameMouseClicked(evt);
            }
        });
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        regPanel.add(lastName);
        lastName.setBounds(20, 120, 170, 30);

        jButton5.setBackground(new java.awt.Color(0, 102, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Sign-up");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        regPanel.add(jButton5);
        jButton5.setBounds(100, 370, 90, 22);

        regPass.setForeground(new java.awt.Color(0, 102, 255));
        regPass.setText("Password");
        regPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regPassMouseClicked(evt);
            }
        });
        regPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPassActionPerformed(evt);
            }
        });
        regPanel.add(regPass);
        regPass.setBounds(20, 280, 240, 30);

        regUsername.setForeground(new java.awt.Color(0, 102, 255));
        regUsername.setText("Username");
        regUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regUsernameMouseClicked(evt);
            }
        });
        regUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUsernameActionPerformed(evt);
            }
        });
        regPanel.add(regUsername);
        regUsername.setBounds(20, 240, 240, 30);

        mainPanel.add(regPanel);
        regPanel.setBounds(440, 20, 280, 440);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/login bg.jpg"))); // NOI18N
        mainPanel.add(background);
        background.setBounds(0, 0, 739, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userActionPerformed

    private void middleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void signinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtnActionPerformed
        // TODO add your handling code here:
        regPanel.show();
        loginPanel.hide();
        
        
    }//GEN-LAST:event_signinbtnActionPerformed

    private void regPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPassActionPerformed

    private void regUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUsernameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        regUser();
        MainMenu main = new MainMenu();
                main.setVisible(true);
      
                this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void regLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLoginActionPerformed
        // TODO add your handling code here:
        loginPanel.setVisible(true);
        regPanel.setVisible(false);
    }//GEN-LAST:event_regLoginActionPerformed

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        if(user.getText().equals("Username")){
            user.setText("");
        }
    }//GEN-LAST:event_userMouseClicked

    private void firstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstNameMouseClicked
        // TODO add your handling code here:
        if(firstName.getText().equals("First Name")){
            firstName.setText("");
        }
    }//GEN-LAST:event_firstNameMouseClicked

    private void middleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_middleMouseClicked
        // TODO add your handling code here:
        if(middle.getText().equals("M.I")){
            middle.setText("");
        }
    }//GEN-LAST:event_middleMouseClicked

    private void lastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastNameMouseClicked
        // TODO add your handling code here:
        if(lastName.getText().equals("Last Name")){
            lastName.setText("");
        }
    }//GEN-LAST:event_lastNameMouseClicked

    private void ageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ageMouseClicked
        // TODO add your handling code here:
        if(age.getText().equals("Age")){
            age.setText("");
        }
    }//GEN-LAST:event_ageMouseClicked

    private void addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressMouseClicked
        // TODO add your handling code here:
        if(address.getText().equals("Address")){
            address.setText("");
        }
    }//GEN-LAST:event_addressMouseClicked

    private void courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseClicked
        // TODO add your handling code here:
        if(course.getText().equals("Course")){
            course.setText("");
        }
    }//GEN-LAST:event_courseMouseClicked

    private void regUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regUsernameMouseClicked
        // TODO add your handling code here:
        if(regUsername.getText().equals("Username")){
            regUsername.setText("");
        }
    }//GEN-LAST:event_regUsernameMouseClicked

    private void regPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regPassMouseClicked
        // TODO add your handling code here:
        if(regPass.getText().equals("Password")){
            regPass.setText("");
        }
    }//GEN-LAST:event_regPassMouseClicked

    private void pass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass1MouseClicked
        // TODO add your handling code here:
        if(pass1.getText().equals("Re-type Password")){
            pass1.setText("");
        }
    }//GEN-LAST:event_pass1MouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passActionPerformed

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
        // TODO add your handling code here:
        pass.setText("");
    }//GEN-LAST:event_passMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> block;
    private javax.swing.JTextField course;
    private javax.swing.JLabel errorlbl;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastName;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField middle;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField pass1;
    private javax.swing.JButton regLogin;
    private javax.swing.JPanel regPanel;
    private javax.swing.JTextField regPass;
    private javax.swing.JTextField regUsername;
    private javax.swing.JCheckBox remCheckBox;
    private javax.swing.JButton signinbtn;
    private javax.swing.JTextField user;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
