/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bisulibraryarchives;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Keth Dominic
 */
public class MainMenu extends javax.swing.JFrame {
    
    DefaultTableModel model;
    Object tablerow [][];
    String tablecol []= {"Book Name","Type","Year","Publisher","Author","Status","Qty"};
    String order = "ASC", columnSelected = "book_name";
    String preSearch="";
    
    /**
     * Creates new form MainMenu
     */
    
    QueryProcessor qp;
    public MainMenu() {
        initComponents();
        qp = new QueryProcessor ();
        menuPanel.setVisible(false);
        search();
  
    }
    
    public void search(){
        String searchQuery = "SELECT `book_name`, `type`, `year`, `publisher`, `author`, `status`, `quantity` FROM `book_list` WHERE `"+columnSelected+"` "
                +"LIKE'%"+preSearch+"%' ORDER BY `"+columnSelected+"` "+order+"";
        
                //System.out.println(searchQuery);
        tablerow = qp.getAllRecord(searchQuery);
        model = new DefaultTableModel(tablerow,tablecol);
        
        searchTable.setModel(model);
        searchTable.getColumnModel().getColumn(0).setPreferredWidth(150);
        searchTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        searchTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        searchTable.getColumnModel().getColumn(6).setPreferredWidth(30);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        menuPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backgroudn = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        orderBy = new javax.swing.JComboBox<>();
        column = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 0, 310, 480);

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuPanel.add(jButton1);
        jButton1.setBounds(20, 100, 260, 40);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Library Management");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        menuPanel.add(jButton2);
        jButton2.setBounds(20, 50, 260, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/icons8_back_30px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        menuPanel.add(jLabel4);
        jLabel4.setBounds(270, 10, 40, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/icons8_user_shield_30px.png"))); // NOI18N
        menuPanel.add(jLabel6);
        jLabel6.setBounds(10, 10, 40, 30);

        backgroudn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/menu.png"))); // NOI18N
        menuPanel.add(backgroudn);
        backgroudn.setBounds(0, 0, 310, 480);
        menuPanel.add(jButton3);
        jButton3.setBounds(0, 0, 310, 480);

        jPanel1.add(menuPanel);
        menuPanel.setBounds(0, 0, 310, 480);

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Book Name", "Type", "Year", "Publisher", "Author", "Status", "Qty"
            }
        ));
        jScrollPane1.setViewportView(searchTable);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(tablePanel);
        tablePanel.setBounds(30, 100, 680, 360);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BISU Library and Archives");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 10, 300, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/icons8_search_28px_1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 50, 40, 50);

        search.setText("Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(20, 62, 260, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/icons8_circled_user_male_skin_type_7_30px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 20, 40, 30);

        orderBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASC", "DESC" }));
        orderBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderByActionPerformed(evt);
            }
        });
        jPanel1.add(orderBy);
        orderBy.setBounds(430, 60, 70, 30);

        column.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book Name", "Type", "Year", "Publisher", "Author", "Status", "Quantity" }));
        column.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnActionPerformed(evt);
            }
        });
        jPanel1.add(column);
        column.setBounds(320, 60, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/BISU-LOGO BG2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(380, 0, 50, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisulibraryarchives/pictures/bg.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 740, 480);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jLayeredPane1);
        jLayeredPane1.setBounds(0, -10, 100, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        //search();
       
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        preSearch = search.getText();
        search();
 
    }//GEN-LAST:event_searchKeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
       
        menuPanel.setVisible(true);
        //tablePanel.setVisible(false);
        
     
        searchTable.setAutoCreateRowSorter(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        
        tablePanel.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void orderByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderByActionPerformed
        // TODO add your handling code here:
        if(orderBy.getSelectedItem().equals("DESC")){
            order = "DESC";
        }
        else{
            order = "ASC";
        }
        search();
    }//GEN-LAST:event_orderByActionPerformed

    private void columnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnActionPerformed
        // TODO add your handling code here:
        if(column.getSelectedItem().equals("Book Name")){
            columnSelected = "book_name";
        }
        else if (column.getSelectedItem().equals("Type")){
            columnSelected = "type";
        }
        else if (column.getSelectedItem().equals("Year")){
            columnSelected = "year";
        }
        else if (column.getSelectedItem().equals("Publisher")){
            columnSelected = "publisher";
        }
        else if (column.getSelectedItem().equals("Author")){
            columnSelected = "author";
        }
        else if (column.getSelectedItem().equals("Status")){
            columnSelected = "status";
        }
        else if (column.getSelectedItem().equals("Quantity")){
            columnSelected = "quantity";
        }
        search();
    }//GEN-LAST:event_columnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginPanel login = new LoginPanel();
        login.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        if(search.getText().equals("Search")){
            search.setText("");
        }
    }//GEN-LAST:event_searchMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Settings settings = new Settings();
        settings.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroudn;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> column;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JComboBox<String> orderBy;
    private javax.swing.JTextField search;
    private javax.swing.JTable searchTable;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
