/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bisulibraryarchives;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Keth Dominic
 */
public class Settings extends javax.swing.JFrame {
    DefaultTableModel model;
    Object tablerow [][];
    String tablecol []= {"Book Name","Type","Year","Publisher","Author","Status","Qty"};
    

    /**
     * Creates new form Settings
     */
    
    QueryProcessor qp;
    public Settings() {
        initComponents();
        qp = new QueryProcessor();
        search();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void search(){
        String searchQuery = "SELECT `book_name`, `type`, `year`, `publisher`, `author`, `status`, `quantity` FROM `book_list` ORDER BY `book_name` ASC";
        
                //System.out.println(searchQuery);
        tablerow = qp.getAllRecord(searchQuery);
        model = new DefaultTableModel(tablerow,tablecol);
        
        searchTable.setModel(model);
        searchTable.getColumnModel().getColumn(0).setPreferredWidth(150);
        searchTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        searchTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        searchTable.getColumnModel().getColumn(6).setPreferredWidth(30);
        
        
    }
    
    public void addBook(){
        qp.executeUpdate("Insert into `book_list` values(NULL,'"+bookName.getText()
            +"','"+bookType.getSelectedItem()+"','"+bookYear.getText()
            +"','"+publisher.getText()+"','"+author.getText()+"','"+status.getSelectedItem()+"'"
                    + ",'"+quantity.getText()+"') ");
    search();
    }
    
    public String getBookName(){
    return model.getValueAt(searchTable.getSelectedRow(),0).toString();
    }
    
    public void setDataToFields(){
        bookName1.setText(qp.getSpecificField("Select `book_name` from `book_list` where `book_name` ='"+getBookName()+"'"));
        bookType1.setSelectedItem(qp.getSpecificField("Select `type` from `book_list` where `book_name` ='"+getBookName()+"'"));
        bookYear1.setText(qp.getSpecificField("Select `year` from `book_list` where `book_name` ='"+getBookName()+"'"));
        publisher1.setText(qp.getSpecificField("Select `publisher` from `book_list` where `book_name` ='"+getBookName()+"'"));
        author1.setText(qp.getSpecificField("Select `author` from `book_list` where `book_name` ='"+getBookName()+"'"));
        status1.setSelectedItem(qp.getSpecificField("Select `status` from `book_list` where `book_name` ='"+getBookName()+"'"));
        quantity1.setText(qp.getSpecificField("Select `quantity` from `book_list` where `book_name` ='"+getBookName()+"'"));
    }
    
    public void save(){
        qp.executeUpdate("Update `book_list` SET `book_name`='"+bookName1.getText()+"',`type`='"+bookType1.getSelectedItem()+
                "',`year`='"+bookYear1.getText()+"',`publisher`='"+publisher1.getText()+"',`author`='"+author1.getText()+"',`status`='"+status1.getSelectedItem()+
                "',`quantity`='"+quantity1.getText()+"' WHERE `book_name` ='"+getBookName()+"'");
        search();
    }
    
    public void deleteData(){
        qp.executeUpdate("delete from `book_list` where `book_list`.`book_name`='"+getBookName()+"'");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBookMini = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bookName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        publisher = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        bookYear = new javax.swing.JTextField();
        bookType = new javax.swing.JComboBox<>();
        addBookBtn = new javax.swing.JButton();
        editBookMini = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        bookName1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        publisher1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        author1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        quantity1 = new javax.swing.JTextField();
        status1 = new javax.swing.JComboBox<>();
        bookYear1 = new javax.swing.JTextField();
        bookType1 = new javax.swing.JComboBox<>();
        saveBook = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addBook = new javax.swing.JButton();
        deleteBook = new javax.swing.JButton();
        editBook = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();

        addBookMini.setMinimumSize(new java.awt.Dimension(425, 344));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add Book");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 220, 30);

        jPanel4.setLayout(null);

        jLabel2.setText("Book Name:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 10, 70, 20);
        jPanel4.add(bookName);
        bookName.setBounds(90, 10, 280, 22);

        jLabel3.setText("Type:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 40, 70, 20);

        jLabel4.setText("Book Year:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 70, 70, 20);

        jLabel5.setText("Publisher:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 100, 70, 20);
        jPanel4.add(publisher);
        publisher.setBounds(90, 100, 280, 22);

        jLabel6.setText("Author:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 130, 70, 20);
        jPanel4.add(author);
        author.setBounds(90, 130, 280, 22);

        jLabel8.setText("Status:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 160, 70, 20);

        jLabel9.setText("Quantity:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 190, 70, 20);
        jPanel4.add(quantity);
        quantity.setBounds(90, 190, 100, 22);

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));
        jPanel4.add(status);
        status.setBounds(90, 160, 100, 22);
        jPanel4.add(bookYear);
        bookYear.setBounds(90, 70, 100, 22);

        bookType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantasy", "Fiction", "Horror", "Sci-Fi" }));
        jPanel4.add(bookType);
        bookType.setBounds(90, 40, 100, 22);

        addBookBtn.setText("Add Book");
        addBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBtnActionPerformed(evt);
            }
        });
        jPanel4.add(addBookBtn);
        addBookBtn.setBounds(275, 220, 90, 22);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 40, 380, 250);

        javax.swing.GroupLayout addBookMiniLayout = new javax.swing.GroupLayout(addBookMini.getContentPane());
        addBookMini.getContentPane().setLayout(addBookMiniLayout);
        addBookMiniLayout.setHorizontalGroup(
            addBookMiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        addBookMiniLayout.setVerticalGroup(
            addBookMiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        editBookMini.setMinimumSize(new java.awt.Dimension(425, 344));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Edit Book");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(10, 10, 220, 30);

        jPanel8.setLayout(null);

        jLabel19.setText("Book Name:");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(10, 10, 70, 20);
        jPanel8.add(bookName1);
        bookName1.setBounds(90, 10, 280, 22);

        jLabel20.setText("Type:");
        jPanel8.add(jLabel20);
        jLabel20.setBounds(10, 40, 70, 20);

        jLabel21.setText("Book Year:");
        jPanel8.add(jLabel21);
        jLabel21.setBounds(10, 70, 70, 20);

        jLabel22.setText("Publisher:");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(10, 100, 70, 20);
        jPanel8.add(publisher1);
        publisher1.setBounds(90, 100, 280, 22);

        jLabel23.setText("Author:");
        jPanel8.add(jLabel23);
        jLabel23.setBounds(10, 130, 70, 20);
        jPanel8.add(author1);
        author1.setBounds(90, 130, 280, 22);

        jLabel24.setText("Status:");
        jPanel8.add(jLabel24);
        jLabel24.setBounds(10, 160, 70, 20);

        jLabel25.setText("Quantity:");
        jPanel8.add(jLabel25);
        jLabel25.setBounds(10, 190, 70, 20);
        jPanel8.add(quantity1);
        quantity1.setBounds(90, 190, 100, 22);

        status1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));
        jPanel8.add(status1);
        status1.setBounds(90, 160, 100, 22);
        jPanel8.add(bookYear1);
        bookYear1.setBounds(90, 70, 100, 22);

        bookType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantasy", "Fiction", "Horror", "Sci-Fi" }));
        jPanel8.add(bookType1);
        bookType1.setBounds(90, 40, 100, 22);

        saveBook.setText("Save");
        saveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBookActionPerformed(evt);
            }
        });
        jPanel8.add(saveBook);
        saveBook.setBounds(275, 220, 90, 22);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(10, 40, 380, 250);

        javax.swing.GroupLayout editBookMiniLayout = new javax.swing.GroupLayout(editBookMini.getContentPane());
        editBookMini.getContentPane().setLayout(editBookMiniLayout);
        editBookMiniLayout.setHorizontalGroup(
            editBookMiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        editBookMiniLayout.setVerticalGroup(
            editBookMiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Library Management");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 10, 250, 30);

        addBook.setText("Add Book");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        deleteBook.setText("Delete Book");
        deleteBook.setEnabled(false);
        deleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookActionPerformed(evt);
            }
        });

        editBook.setText("Edit Book");
        editBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBook, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(editBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBook)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 50, 110, 290);

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Book Name", "Type", "Year", "Publisher", "Author", "Status", "Qty"
            }
        ));
        searchTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                searchTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        searchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(searchTable);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(130, 50, 530, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        // TODO add your handling code here:
        addBookMini.setVisible(true);
        addBookMini.setLocationRelativeTo(null);
        

    }//GEN-LAST:event_addBookActionPerformed

    private void addBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBtnActionPerformed
        // TODO add your handling code here:
        addBook();
    }//GEN-LAST:event_addBookBtnActionPerformed

    private void editBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookActionPerformed
        // TODO add your handling code here:
        editBookMini.setVisible(true);
        editBookMini.setLocationRelativeTo(null);
    }//GEN-LAST:event_editBookActionPerformed

    private void searchTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_searchTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTableAncestorAdded

    private void searchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTableMouseClicked
        // TODO add your handling code here:
        deleteBook.setEnabled(true);
        getBookName();
        setDataToFields();
    }//GEN-LAST:event_searchTableMouseClicked

    private void saveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBookActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_saveBookActionPerformed

    private void deleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Confirm delete this row?", "BISU Library and Archives",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,  null);
        if(confirm == JOptionPane.YES_OPTION){
            deleteData();
            search();
        }
    }//GEN-LAST:event_deleteBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JButton addBookBtn;
    private javax.swing.JDialog addBookMini;
    private javax.swing.JTextField author;
    private javax.swing.JTextField author1;
    private javax.swing.JTextField bookName;
    private javax.swing.JTextField bookName1;
    private javax.swing.JComboBox<String> bookType;
    private javax.swing.JComboBox<String> bookType1;
    private javax.swing.JTextField bookYear;
    private javax.swing.JTextField bookYear1;
    private javax.swing.JButton deleteBook;
    private javax.swing.JButton editBook;
    private javax.swing.JDialog editBookMini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField publisher;
    private javax.swing.JTextField publisher1;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField quantity1;
    private javax.swing.JButton saveBook;
    private javax.swing.JTable searchTable;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JComboBox<String> status1;
    // End of variables declaration//GEN-END:variables
}
